name: Build Arch Linux ISO

on:
  push:
    branches:
      - main
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    permissions:
      contents: write

    container:
      image: archlinux:latest
      options: --privileged

    steps:
      - uses: actions/checkout@v2

      - name: Change directory to iso/archiso
        run: cd iso/archiso

      - name: Install archiso
        run: sudo pacman -Sy archiso --noconfirm

      - name: Set current date as environment variable
        run: echo "DATE=$(date +'%Y.%m.%d')" >> $GITHUB_ENV

      - name: Run build-iso script
        run: bash makeiso.bash

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.dev == 'true' }}
        with:
          name: klindos-${{ env.DATE }}-x86_64.iso
          path: iso/archiso/output/klindos-${{ env.DATE }}-x86_64.iso
