name: Build Archiso Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: arch-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Install Dependencies
      run: |
        sudo pacman -Syu --noconfirm
        sudo pacman -S --noconfirm archiso
        
    - name: Build Archiso Image
      run: |
        cd iso/archiso
        sudo mkarchiso -v -w ../output -o ../output releng/
