name: Build Arch Linux ISO

on:
  push:
    branches:
      - main
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    permissions:
      contents: write

    container:
      image: archlinux:latest
      options: --privileged

    steps:
      - uses: actions/checkout@v2

      - name: Set current date as environment variable
        run: echo "DATE=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
        working-directory: /iso/archiso

      - name: Run build-iso script
        run: bash makeiso.bash
        working-directory: /iso/archiso

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.dev == 'true' }}
        with:
          name: Arch Linux ${{ env.DATE }}
          path: |
            /iso/archiso/archlinux-${{ env.DATE }}-x86_64.iso
            /iso/archiso/CHECKSUMS.txt
